zenuml

title POST User Sign Up endpoint

@AzureFunction be as "Back End" 
@Database db as "Database"

be."POST /users" {
    be.validateUserCreation() {
        areInputsValid() {
            // rules:
            // - Inputs are not SQL injection
            // - First name is valid
            // - Email is valid
            return
        }
        isUserAlreadyExists() {
            be->db."query if record exists" { return result }
        }
    }
    if("validation failure") { return "422 Error" }
    else {
        createUser() {
            be->db."Create record" { return "success" }
        }
        dispatchUserCreatedEvent()
        return "200 OK"
    }
}