zenuml

title POST User Sign Up endpoint

@AzureFunction be as "Back End" 
@Database db as "Database"

be."POST /users" {
    be."Validate User Creation" {
        "Is request content valid?" {
            // rules:
            // - Inputs are not SQL injection
            // - First name is valid
            // - Email is valid
            return
        }
        "Is user already registered?" {
            be->db."query if record exists" { return result }
        }
    }
    if("validation failure") { return "422 Error" }
    else {
        "Create user" {
            be->db."Create record" { return "success" }
        }
        return "200 OK"
    }
}